export const coffeeDatabase = [
  {
    id: '1',
    image: 'expresso-tradicional.png',
    tags: ['Tradicional'],
    title: 'Expresso Tradicional',
    paragraph: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '2',
    image: 'expresso-americano.png',
    tags: ['Tradicional'],
    title: 'Expresso Americano',
    paragraph: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '3',
    image: 'expresso-cremoso.png',
    tags: ['Tradicional'],
    title: 'Expresso Cremoso',
    paragraph: 'Café expresso tradicional com espuma cremosa',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '4',
    image: 'expresso-gelado.png',
    tags: ['Tradicional', 'Gelado'],
    title: 'Expresso Gelado',
    paragraph: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '5',
    image: 'cafe-leite.png',
    tags: ['Tradicional', 'Com leite'],
    title: 'Café com Leite',
    paragraph: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '6',
    image: 'latte.png',
    tags: ['Tradicional', 'Com leite'],
    title: 'Latte',
    paragraph:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '7',
    image: 'capuccino.png',
    tags: ['Tradicional', 'Com leite'],
    title: 'Capuccino',
    paragraph:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '8',
    image: 'macchiato.png',
    tags: ['Tradicional', 'Com leite'],
    title: 'Macchiato',
    paragraph: 'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '9',
    image: 'mocaccino.png',
    tags: ['Tradicional', 'Com leite'],
    title: 'Mocaccino',
    paragraph: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '10',
    image: 'chocolate-quente.png',
    tags: ['Especial', 'Com leite'],
    title: 'Chocolate Quente',
    paragraph: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '11',
    image: 'cubano.png',
    tags: ['Especial', 'Alcoólico', 'Gelado'],
    title: 'Cubano',
    paragraph:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '12',
    image: 'havaiano.png',
    tags: ['Especial'],
    title: 'Havaiano',
    paragraph: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '13',
    image: 'arabe.png',
    tags: ['Especial'],
    title: 'Árabe',
    paragraph: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
  {
    id: '14',
    image: 'irlandes.png',
    tags: ['Especial', 'Alcoólico'],
    title: 'Irlandês',
    paragraph: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
    quantity: 1,
    totalPrice: 0,
  },
];
